// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package todos

func TodoPostToTodo(src *TodosPostRequest) (dst *Todo) {
	dst = &Todo{}
	// skip: dst.BaseModel
	// skip: dst.Id
	dst.Title = src.Title
	dst.Content = src.Content
	// skip: dst.Complete

	return
}

func TodoPutToTodo(src *TodosPutByIdRequest) (dst *Todo) {
	dst = &Todo{}
	// skip: dst.BaseModel
	// skip: dst.Id
	dst.Title = src.Title
	dst.Content = src.Content
	dst.Complete = src.Complete

	return
}

func TodoToListing(src *Todo) (dst *TodoListing) {
	dst = &TodoListing{}
	dst.Id = src.Id
	dst.Title = src.Title
	dst.Complete = src.Complete

	return
}
