/*
 * Symbolic Boilerplate
 *
 * An API spec for managing todo lists
 *
 * API version: 1.0.0
 * Contact: contact@simonball.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todos

import "github.com/uptrace/bun"

type Todo struct {
	bun.BaseModel `bun:"table:todos"`
	Id            int64  `json:"id" bun:"id,pk,autoincrement"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	Complete      bool   `json:"complete"`
}

type TodoListing struct {
	Id       int64  `json:"id"`
	Title    string `json:"title"`
	Complete bool   `json:"complete"`
}
